python3 ./src/image_downloader.py A &
python3 ./src/image_downloader.py B &
python3 ./src/image_downloader.py C &
python3 ./src/image_downloader.py D &
python3 ./src/image_downloader.py E &
python3 ./src/image_downloader.py F &
python3 ./src/image_downloader.py G &
python3 ./src/image_downloader.py H &
python3 ./src/image_downloader.py I &
python3 ./src/image_downloader.py J &
python3 ./src/image_downloader.py K &
python3 ./src/image_downloader.py L &
python3 ./src/image_downloader.py M &
python3 ./src/image_downloader.py N &
python3 ./src/image_downloader.py O &
python3 ./src/image_downloader.py P &
python3 ./src/image_downloader.py Q &
python3 ./src/image_downloader.py R &
python3 ./src/image_downloader.py S &
python3 ./src/image_downloader.py T &
python3 ./src/image_downloader.py U &
python3 ./src/image_downloader.py V &
python3 ./src/image_downloader.py W &
python3 ./src/image_downloader.py X &
python3 ./src/image_downloader.py Y &
